-- ================================================================
-- ARCHIVO: fase_avanzada_proyecto_oracle.sql
-- PROYECTO: Tienda de Dispositivos Móviles (Versión Oracle 23ai)
-- ASIGNATURA: Bases de Datos Avanzadas
-- MOTOR DE BASE DE DATOS: Oracle Cloud / FreeSQL (PL/SQL)
-- ================================================================

-- ==================================================
-- BLOQUE 0: LIMPIEZA DE OBJETOS PREEXISTENTES
-- ==================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW vista_cliente_catalogo'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW vista_tecnico_panel'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW vista_gerencial_reporte'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW vista_gerencial_segura'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE detalles_mantenimiento CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE inventario_celulares CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE sesion_simulada CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ==================================================
-- BLOQUE 1: DDL Y DATOS INICIALES (Fase 1)
-- ==================================================

-- Tabla 1: Productos del negocio
CREATE TABLE inventario_celulares (
    celular_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo VARCHAR2(100) NOT NULL,
    stock INT NOT NULL,
    precio NUMBER(10,2) NOT NULL,
    costo_interno NUMBER(10,2),
    CONSTRAINT chk_stock_no_negativo CHECK (stock >= 0)
);

-- Tabla 2: Servicios prestados
CREATE TABLE detalles_mantenimiento (
    servicio_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    celular_id INT,
    tecnico VARCHAR2(100) NOT NULL,
    repuestos_usados INT DEFAULT 0,
    fecha_servicio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    costo_repuestos NUMBER(10,2),
    CONSTRAINT fk_celular_servicio
        FOREIGN KEY (celular_id) REFERENCES inventario_celulares(celular_id)
        ON DELETE CASCADE
);

-- Tabla de Control: Simulación de Contexto de Sesión para DCL
CREATE TABLE sesion_simulada (
    usuario_activo VARCHAR2(50),
    rol_activo VARCHAR2(50)
);

-- Inserción de Datos Iniciales Basificados
INSERT INTO inventario_celulares (modelo, stock, precio, costo_interno)
VALUES ('iPhone 15 Pro Max', 4, 5500000.00, 3800000.00);

INSERT INTO inventario_celulares (modelo, stock, precio, costo_interno)
VALUES ('Samsung Galaxy S24 Ultra', 3, 4800000.00, 3200000.00);

INSERT INTO inventario_celulares (modelo, stock, precio, costo_interno)
VALUES ('Xiaomi 14 Ultra', 6, 3200000.00, 1900000.00);

INSERT INTO detalles_mantenimiento (celular_id, tecnico, repuestos_usados, costo_repuestos)
VALUES (1, 'Tecnico Carlos', 1, 85000.00);

INSERT INTO detalles_mantenimiento (celular_id, tecnico, repuestos_usados, costo_repuestos)
VALUES (2, 'Tecnico Maria', 0, 0.00);

-- Inicializamos la sesión por defecto como Administrador
INSERT INTO sesion_simulada (usuario_activo, rol_activo) 
VALUES ('ADMIN_TIENDA', 'ROL_ADMIN');

COMMIT;


-- ==================================================
-- BLOQUE 2: AUTOMATIZACIÓN (TRIGGERS Y PROCEDURES)
-- ==================================================

-- TRIGGER: Gestión de Inventario mediante Mantenimientos
CREATE OR REPLACE TRIGGER trg_procesar_mantenimiento
AFTER INSERT ON detalles_mantenimiento
FOR EACH ROW
BEGIN
    IF :NEW.repuestos_usados > 0 THEN
        UPDATE inventario_celulares
        SET stock = stock - :NEW.repuestos_usados
        WHERE celular_id = :NEW.celular_id;
    END IF;
END;
/

-- STORED PROCEDURE: Venta Atómica con Manejo Controlado de Excepciones
CREATE OR REPLACE PROCEDURE sp_registrar_venta(
    p_celular_id IN INT,
    p_cantidad IN INT
)
IS
    v_stock_actual INT;
    stock_insuficiente EXCEPTION;
    error_interno EXCEPTION;
    PRAGMA EXCEPTION_INIT(error_interno, -20002);
BEGIN
    -- Bloqueo explícito de fila (Pessimistic Locking)
    SELECT stock INTO v_stock_actual 
    FROM inventario_celulares 
    WHERE celular_id = p_celular_id FOR UPDATE;
    
    IF v_stock_actual >= p_cantidad THEN
        UPDATE inventario_celulares
        SET stock = stock - p_cantidad
        WHERE celular_id = p_celular_id;
        COMMIT;
    ELSE
        RAISE stock_insuficiente;
    END IF;

EXCEPTION
    WHEN stock_insuficiente THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'Stock insuficiente para la venta.');
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20002, 'Transacción abortada: Error interno de base de datos.');
END;
/

-- PROCEDIMIENTO: Manejo Contextual del Cambio de Roles Dinámicos
CREATE OR REPLACE PROCEDURE sp_cambiar_sesion(
    p_usuario IN VARCHAR2,
    p_rol IN VARCHAR2
) IS
BEGIN
    UPDATE sesion_simulada 
    SET usuario_activo = UPPER(p_usuario), 
        rol_activo = UPPER(p_rol);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('CAMBIO DE CONTEXTO DE SEGURIDAD EXITOSO');
    DBMS_OUTPUT.PUT_LINE('Usuario Activo: ' || UPPER(p_usuario) || ' | Rol Asignado: ' || UPPER(p_rol));
    DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
END;
/


-- ==================================================
-- BLOQUE 3: SEGURIDAD LÓGICA (VISTAS CONTEXTUALES)
-- ==================================================

-- Vista 1: Catálogo Público (Clientes)
CREATE OR REPLACE VIEW vista_cliente_catalogo AS
SELECT
    celular_id,
    modelo,
    precio AS precio_venta,
    CASE
        WHEN stock = 0 THEN 'Agotado'
        WHEN stock <= 2 THEN 'Últimas unidades'
        ELSE 'En stock'
    END AS disponibilidad
FROM inventario_celulares
WHERE stock >= 0;

-- Vista 2: Panel Operativo (Técnicos)
CREATE OR REPLACE VIEW vista_tecnico_panel AS
SELECT
    ic.celular_id,
    ic.modelo,
    ic.stock AS repuestos_disponibles,
    dm.servicio_id,
    dm.tecnico,
    dm.repuestos_usados,
    dm.fecha_servicio,
    dm.costo_repuestos
FROM inventario_celulares ic
LEFT JOIN detalles_mantenimiento dm ON ic.celular_id = dm.celular_id
ORDER BY dm.fecha_servicio DESC;

-- Vista 3: Reporte General Crudo (Admin Base)
CREATE OR REPLACE VIEW vista_gerencial_reporte AS
SELECT
    ic.modelo,
    ic.stock AS stock_actual,
    ic.precio AS precio_venta,
    ic.costo_interno,
    ROUND(((ic.precio - ic.costo_interno) / ic.precio) * 100, 1) AS margen_pct,
    COUNT(dm.servicio_id) AS total_servicios,
    NVL(SUM(dm.repuestos_usados), 0) AS repuestos_consumidos,
    NVL(SUM(dm.costo_repuestos), 0) AS gasto_repuestos,
    CASE
        WHEN ic.stock = 0 THEN 'CRÍTICO: Sin stock'
        WHEN ic.stock <= 2 THEN 'ALERTA: Stock bajo'
        ELSE 'Normal'
    END AS estado_inventario
FROM inventario_celulares ic
LEFT JOIN detalles_mantenimiento dm ON ic.celular_id = dm.celular_id
GROUP BY ic.modelo, ic.stock, ic.precio, ic.costo_interno;

-- Vista 4: Reporte con Ofuscación por Rol (Simulación DCL Dinámica)
CREATE OR REPLACE VIEW vista_gerencial_segura AS
SELECT
    ic.modelo,
    ic.stock AS stock_actual,
    CASE 
        WHEN (SELECT rol_activo FROM sesion_simulada FETCH FIRST 1 ROWS ONLY) = 'ROL_ADMIN' THEN ic.precio 
        ELSE NULL 
    END AS precio_venta,
    CASE 
        WHEN (SELECT rol_activo FROM sesion_simulada FETCH FIRST 1 ROWS ONLY) = 'ROL_ADMIN' THEN ic.costo_interno 
        ELSE NULL 
    END AS costo_interno,
    CASE 
        WHEN (SELECT rol_activo FROM sesion_simulada FETCH FIRST 1 ROWS ONLY) = 'ROL_ADMIN' THEN ROUND(((ic.precio - ic.costo_interno) / ic.precio) * 100, 1)
        ELSE 0 
    END AS margen_pct
FROM inventario_celulares ic;
/


-- =================================================================
-- BLOQUE 4: BANCO DE PRUEBAS AUTOMATIZADO Y SECUENCIAL
-- =================================================================

-- Activar consola de salida
SET SERVEROUTPUT ON;

-- 1. Verificación e Inspección Inicial del Catálogo de Objetos
SELECT 'inventario_celulares' AS tabla, COUNT(*) AS registros FROM inventario_celulares 
UNION ALL 
SELECT 'detalles_mantenimiento', COUNT(*) FROM detalles_mantenimiento;

SELECT view_name AS vistas_compiladas_exitosamente FROM user_views;

-- 2. Pruebas de Transacciones y Concurrencia (ACID)
SELECT * FROM inventario_celulares WHERE celular_id = 1 FOR UPDATE NOWAIT;
SELECT * FROM inventario_celulares WHERE celular_id = 2 FOR UPDATE WAIT 5;

-- 3. Pruebas de Automatización (Trigger en Acción)
-- Al insertar un repuesto usado, el stock del Xiaomi (ID: 3) cae de 6 a 5 de manera automatizada.
INSERT INTO detalles_mantenimiento (celular_id, tecnico, repuestos_usados, costo_repuestos) 
VALUES (3, 'Tecnico Carlos', 1, 45000.00);

-- 4. Pruebas de Automatización (Procedure en Acción)
-- Al llamar a la venta, disminuye el stock del iPhone (ID: 1) de 4 a 2 de manera controlada.
BEGIN
    sp_registrar_venta(1, 2);
END;
/


-- ----------------------------------------------------------------
-- ESCENARIO DE SIMULACIÓN DE ROLES 1: ROL_CLIENTE_PUBLICO
-- ----------------------------------------------------------------
BEGIN
    sp_cambiar_sesion('sofia_cliente', 'ROL_CLIENTE_PUBLICO');
END;
/

-- Consulta autorizada para Clientes: Ven el catálogo con normalidad
SELECT * FROM vista_cliente_catalogo;

-- Consulta RESTRINGIDA para Clientes: Los costos de la vista protegida retornan NULL/0
SELECT * FROM vista_gerencial_segura;


-- ----------------------------------------------------------------
-- ESCENARIO DE SIMULACIÓN DE ROLES 2: ROL_TECNICO_VENDEDOR
-- ----------------------------------------------------------------
BEGIN
    sp_cambiar_sesion('carlos_perez', 'ROL_TECNICO_VENDEDOR');
END;
/

-- Consulta autorizada para Técnicos: Acceso al historial operativo del taller
SELECT * FROM vista_tecnico_panel;


-- ----------------------------------------------------------------
-- ESCENARIO DE SIMULACIÓN DE ROLES 3: ROL_ADMIN
-- ----------------------------------------------------------------
BEGIN
    sp_cambiar_sesion('admin_tienda', 'ROL_ADMIN');
END;
/

-- Consulta autorizada para Administradores: Pueden auditar costos internos y el margen real
SELECT * FROM vista_gerencial_segura;